apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ku1xmgyks-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ku1xmgyks-go 
  name: ku1xmgyks-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ku1xmgyks-go 
